version: '3'
services:
  brian-evans-tech:
    container_name: betech
    build: .
    ports:
      - "80:80"
# can't share directories from windows to WSL
#    volumes:
#      - ./:/var/www/html/
    environment:
      db_host: db
  db:
    container_name: bedb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: u787130504_oceans
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/VAR/LIB/MYSQL
volumes:
  db_data: