version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
# bind mounts for live updates during development
    volumes:
      - ./www:/var/www/html/:ro
      - ./src:/var/www/src/:ro
    environment:
      db_host: db
  db:
    build: db
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: u787130504_oceans
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: